version: '2'
services:
  mysql_db:
    image: mysql
    platform: linux/amd64
    restart: always
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: rest_api_services_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  rest_api_services_app:
    image: gradle:7.0.0-jdk11
    working_dir: .
    command: "pwd"
    depends_on:
      - mysql_db